import { trpc } from '../utils/trpc';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
//import { UserName } from '../../common';
import { UserName } from '@trpc-lambda-demo/common';

const Home: NextPage = () => {
  const hello = trpc.useQuery(['hello', { name: UserName.parse('Naoki') }]);
  if (!hello.data) {
    return <div>Loading...</div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{`${hello.data.message}`}</h1>
      </main>
    </div>
  );
};

export default Home;
